### ISSUE TITLE
Date wrong??

### ISSUE THREAD

**Issue by sarahwilson** [LogicWolfe/rubber-chicken-assassin#13]
killer: 100000764423905
vic: 511852582
token: 2227470867|2.Bse6k3GFVN_EEntKP2eG1g__.3600.1298862000-100000764423905|uBKyMHRuwKtqzOEQi46gGQwjDAU

made at 6 pm on sunday the 27th
date in post: "We most insincerely announce the departure of Sarah Wilson on February 28, 2011. "

**Comment by LogicWolfe** [comment]
We now use the iphones kill timestamp in order to avoid timezone issues. This closed by f65904a2a40fb016dd88540b76862caa2cfef613.

**Comment by sarahwilson** [comment]
yay! working
