### ISSUE TITLE
obit text - # of blows isn't correct

### ISSUE THREAD

**Issue by sarahwilson** [LogicWolfe/rubber-chicken-assassin#4]
looks like it's just saying 1 at the moment

"David breathed his last breath shortly after receiving 1 blows to the head from the deadly end of a rubber chicken"

**Comment by LogicWolfe** [comment]
Closed by fe1cab2721c55dcf184c6a9e70c4babac444bd0c. Number of blows is now correct.

**Comment by sarahwilson** [comment]
verified. counts # of letters in the attack string
