### ISSUE TITLE
if vic is not your friend, obit create fails

### ISSUE THREAD

**Issue by sarahwilson** [LogicWolfe/rubber-chicken-assassin#8]
http://www.getexceptional.com/exceptions/8003512

tried to kill nathan after unfriending him and got the above error

**Comment by LogicWolfe** [comment]
Closed by 58935d5b3cd8f7b4c670261678961a6f572d5890. Made the kill creation process more resilient to errors.

**Comment by sarahwilson** [comment]
verified
